name: lynx

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    healthcheck:
      test: "curl -f http://localhost:80 || exit 1"
      interval: 5s
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/nginx/ssl/dev.getlynx.tech.crt:/etc/nginx/dev.getlynx.tech.crt:ro
      - ./.docker/nginx/ssl/dev.getlynx.tech.key:/etc/nginx/dev.getlynx.tech.key:ro
      - ./.docker/nginx/ssl/api.dev.getlynx.tech.crt:/etc/nginx/api.dev.getlynx.tech.crt:ro
      - ./.docker/nginx/ssl/api.dev.getlynx.tech.key:/etc/nginx/api.dev.getlynx.tech.key:ro
    depends_on:
      - client
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
      target: dev
    environment:
      BASIC_AUTH_USER: ${BASIC_AUTH_USER:-test}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD:-test}
    ports:
      - "9090:9090"
      - "40000:40000"
    volumes:
      - ./server:/app
    networks:
      - internal

  client:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/client/Dockerfile
      target: development-dependencies-env
    command: sh -c "npm run dev -- --host 0.0.0.0"
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-HI2YJBqHK0Zz0ibFf564RgKPCFlsBfO9}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-https://dev.getlynx.tech}
      AUTH_DATABASE_URL: ${AUTH_DATABASE_URL:-postgres://postgres:postgres@auth-db:5432/auth_db}
      SERVER_BASE_URL: ${SERVER_BASE_URL:-server:9090}
      SERVER_BASIC_AUTH_USER: ${SERVER_BASIC_AUTH_USER:-test}
      SERVER_BASIC_AUTH_PASSWORD: ${SERVER_BASIC_AUTH_PASSWORD:-test}
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - node-modules-client:/app/node_modules
    networks:
      - internal

  auth-db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${AUTH_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${AUTH_POSTGRES_DB:-auth_db}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d auth_db'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  node-modules-client:
  auth-db-data:

networks:
  internal: