// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anchor.sql

package sqlc

import (
	"context"
)

const createAnchor = `-- name: CreateAnchor :one
INSERT INTO "anchors" (
    anchor_id,
    "x",
    "y"
) VALUES (
$1,
$2,
$3
)
RETURNING id, anchor_id, x, y, created_at, updated_at
`

type CreateAnchorParams struct {
	AnchorID string
	X        float64
	Y        float64
}

func (q *Queries) CreateAnchor(ctx context.Context, arg CreateAnchorParams) (Anchor, error) {
	row := q.db.QueryRowContext(ctx, createAnchor, arg.AnchorID, arg.X, arg.Y)
	var i Anchor
	err := row.Scan(
		&i.ID,
		&i.AnchorID,
		&i.X,
		&i.Y,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllAnchors = `-- name: DeleteAllAnchors :exec
DELETE FROM "anchors"
`

func (q *Queries) DeleteAllAnchors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAnchors)
	return err
}

const getAllAnchors = `-- name: GetAllAnchors :many
SELECT id, anchor_id, x, y, created_at, updated_at
FROM "anchors"
`

func (q *Queries) GetAllAnchors(ctx context.Context) ([]Anchor, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnchors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anchor
	for rows.Next() {
		var i Anchor
		if err := rows.Scan(
			&i.ID,
			&i.AnchorID,
			&i.X,
			&i.Y,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
