// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package sqlc

import (
	"context"
)

const getAllDevices = `-- name: GetAllDevices :many
SELECT id, device_id, status, x, y, created_at, updated_at FROM devices
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Status,
			&i.X,
			&i.Y,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (
    device_id,
    status,
    x,
    y
) VALUES (
    $1,
    $2,
    $3,
    $4
 )
ON CONFLICT (device_id)
    DO UPDATE SET
      status = EXCLUDED.status,
      x = EXCLUDED.x,
      y = EXCLUDED.y
RETURNING id, device_id, status, x, y, created_at, updated_at
`

type UpsertDeviceParams struct {
	DeviceID string
	Status   string
	X        float64
	Y        float64
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, upsertDevice,
		arg.DeviceID,
		arg.Status,
		arg.X,
		arg.Y,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Status,
		&i.X,
		&i.Y,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
