// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID           int64
	BetterAuthID string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Vertex struct {
	ID        uuid.UUID
	PolygonID string
	Longitude float64
	Latitude  float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
