// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vertices.sql

package sqlc

import (
	"context"
)

const createVertex = `-- name: CreateVertex :one
INSERT INTO vertices (
    polygon_id,
    longitude,
    latitude
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, polygon_id, longitude, latitude, created_at, updated_at
`

type CreateVertexParams struct {
	PolygonID string
	Longitude float64
	Latitude  float64
}

func (q *Queries) CreateVertex(ctx context.Context, arg CreateVertexParams) (Vertex, error) {
	row := q.db.QueryRowContext(ctx, createVertex, arg.PolygonID, arg.Longitude, arg.Latitude)
	var i Vertex
	err := row.Scan(
		&i.ID,
		&i.PolygonID,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
