// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "tags": [
                    "root"
                ],
                "summary": "Get root",
                "operationId": "getRoot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Root"
                        }
                    }
                }
            }
        },
        "/devices/position": {
            "post": {
                "tags": [
                    "device"
                ],
                "summary": "UpdateDevicePosition",
                "operationId": "updateDevicePosition",
                "parameters": [
                    {
                        "description": "Device Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.DeviceRequest": {
            "type": "object",
            "required": [
                "device_id",
                "readings"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "readings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Reading"
                    }
                }
            }
        },
        "request.Reading": {
            "type": "object",
            "required": [
                "dist",
                "id",
                "rssi"
            ],
            "properties": {
                "dist": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "rssi": {
                    "type": "integer"
                }
            }
        },
        "response.Root": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Lynx API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
