definitions:
  request.Anchor:
    properties:
      id:
        type: string
      x:
        type: number
      "y":
        type: number
    required:
    - id
    - x
    - "y"
    type: object
  request.AnchorsRequest:
    properties:
      anchors:
        items:
          $ref: '#/definitions/request.Anchor'
        type: array
    required:
    - anchors
    type: object
  request.DeviceRequest:
    properties:
      device_id:
        type: string
      is_active:
        type: boolean
      readings:
        items:
          $ref: '#/definitions/request.Reading'
        type: array
    required:
    - device_id
    - is_active
    - readings
    type: object
  request.Reading:
    properties:
      dist:
        type: integer
      id:
        type: string
      rssi:
        type: integer
    required:
    - dist
    - id
    - rssi
    type: object
  request.ScaleRequest:
    properties:
      meters:
        type: number
      pixels:
        type: number
    required:
    - meters
    - pixels
    type: object
  response.Anchor:
    properties:
      id:
        type: string
      x:
        type: number
      "y":
        type: number
    required:
    - id
    - x
    - "y"
    type: object
  response.Root:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  response.Scale:
    properties:
      meters:
        type: number
      pixels:
        type: number
    required:
    - meters
    - pixels
    type: object
info:
  contact: {}
  title: Lynx API
  version: "1.0"
paths:
  /:
    get:
      operationId: getRoot
      parameters:
      - description: User ID
        in: header
        name: X-User-ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Root'
      summary: Get root
      tags:
      - root
  /anchors:
    get:
      operationId: getAllAnchors
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.Anchor'
            type: array
      summary: GetAllAnchors
      tags:
      - anchor
    post:
      operationId: upsertAnchors
      parameters:
      - description: Anchors Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.AnchorsRequest'
      responses:
        "201":
          description: Created
      summary: UpsertAnchors
      tags:
      - anchor
  /devices/position:
    post:
      operationId: upsertDevicePosition
      parameters:
      - description: Device Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.DeviceRequest'
      responses:
        "200":
          description: OK
      summary: UpsertDevicePosition
      tags:
      - device
  /scales:
    get:
      operationId: getScale
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Scale'
      summary: GetScale
      tags:
      - scale
    post:
      operationId: createScale
      parameters:
      - description: Scale Request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ScaleRequest'
      responses:
        "200":
          description: OK
      summary: CreateScale
      tags:
      - scale
swagger: "2.0"
